In [3]:
import GAUtilities as ga # this is a local package
import numpy as np

np.random.seed(10101010) #for everything, everything, everything... (Courtesy of the Violent Femmes)
pop_size = 6 # should be even due to the way we'll implement crossover
ind_size = 3 #this is the number of genes in each individual

#bounds are used for both real and integer problems. 
#For integer problems, the upper bound should be 1 over what you actually want
bounds = [1,7]

#each type of problem might use different types of populations. This one is a simple matrix of integers.
pop = np.random.randint(low=bounds[0], high=bounds[1], size =(pop_size,ind_size))

def obj_sumDice(x):
    x = np.array(x) # force a numpy arrray here so that the math below works
    return np.sum(x)

#compute the fitness by passing in the function and population
fitness = ga.computeFitness(obj_sumDice, pop)

print('Not sorted')
print(fitness)
print(pop)

pop = ga.sortPop(pop, fitness)#sort population

print('Sorted')
print(pop)

Not sorted
[ 9. 13.  9. 15. 13.  7.]
[[2 3 4]
 [3 6 4]
 [2 3 4]
 [6 4 5]
 [6 2 5]
 [4 1 2]]
Sorted
[[4 1 2]
 [2 3 4]
 [2 3 4]
 [3 6 4]
 [6 2 5]
 [6 4 5]]


array([[4, 1, 2],
       [2, 3, 4],
       [2, 3, 4],
       [3, 6, 4],
       [6, 2, 5],
       [6, 4, 5]])